config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  devise_for :users
  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user
  resources :users

  resources :posts do
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end

  resources :reviews do
    resources :votes do
      collection do
        post 'upvote'
        post 'downvote'
        delete 'unvote'
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index]
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :webseries_name, presence: true
  validates :link, presence: true
  validates :description, presence: true, length: { minimum: 5 }

  def self.search(query)
    where("webseries_name like ?", "%#{query}%")
  end

  def name
    webseries_name
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  def self.ratings
    [
      [1, "1 (Hated It!)"],
      [2, "2 (Kind of terrible.)"],
      [3, "3 (Meh.)"],
      [4, "4 (Pretty good)"],
      [5, "5 (Best thing ever)"]
    ]
  end

  belongs_to :user
  belongs_to :post
  has_many :votes, dependent: :destroy

  validates_presence_of :rating, message: "must be provided!"
  validates_uniqueness_of :user, scope: :post

  def upvote_total
    votes.where(upvote: true).size
  end

  def downvote_total
    votes.where(upvote: false).size
  end
end

app/models/user.rb
class User < ActiveRecord::Base # :nodoc:
  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, presence: true
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :votes, dependent: :destroy

  def admin?
    role == "admin"
  end

  def voted?(id)
    votes.where(review_id: id).exists?
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
  validates :review, presence: true, uniqueness: { scope: :user }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authorize_admin!
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache) }
  end

  def authorize_admin!
    if current_user.nil? || !current_user.admin?
      flash[:notice] = "You are not authorized to view this resource"
      redirect_to root_path
    end
  end
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC").page(params[:page]).per(20)
    else
      @posts = Post.all.order(created_at: :desc).page(params[:page]).per(20)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
    else
      flash[:error] = @post.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @reviews = @post.reviews.order(created_at: :desc).page(params[:page]).per(10)
    @rating_options = Review.ratings
    @review = Review.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post Edited!"
      redirect_to post_path(@post)
    else
      flash[:error] = 'Please complete the form correctly'
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy!
      flash[:notice] = "Post deleted!"
      redirect_to posts_path
    else
      flash[:error] = "What happened?"
      redirect_to post_path(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(
      :webseries_name,
      :link,
      :description
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    if @review.save
      flash[:success] = "Review has been successfully created!"
      # ReviewMailer.new_review(@review).deliver_later
    else
      flash[:error] = @review.errors.full_messages.join(", ")
    end
    redirect_to post_path(@review.post)
  end

  def destroy
    @review = Review.find(params[:id])
    @post = @review.post
    if @review.destroy!
      flash[:notice] = "Review deleted!"
      redirect_to posts_path
    else
      flash[:error] = "What happened?"
      redirect_to post_path(@review.post)
    end
  end

  def edit
    session[:edit] = true
    @review = Review.find(params[:id])
    redirect_to post_path(@review.post)
  end

  def update
    @review = Review.find(params[:id])
    @post = @review.post
    if @review.update(review_params)
      flash[:notice] = "Review Edited!"
      redirect_to post_path(@post)
    else
      flash[:error] = "Review edits not saved."
      redirect_to posts_path(@post)
    end
  end

  private

  def review_params
    params.require(:review).permit(
      :rating,
      :body
    ).merge(post: Post.find(params[:post_id]), user: current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
      flash[:notice] = "User is no more!"
      redirect_to admin_users_path
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :before_vote

  def upvote
    @this_vote.upvote = true
    @this_vote.save
    render json: { uvTotal: @this_vote.review.upvote_total, dvTotal: @this_vote.review.downvote_total }
  end

  def downvote
    @this_vote.upvote = false
    @this_vote.save
    render json: { uvTotal: @this_vote.review.upvote_total, dvTotal: @this_vote.review.downvote_total }
  end

  def unvote
    @this_vote.destroy
    flash[:notice] = "Your vote has been removed"
    render json: { uvTotal: @this_vote.review.upvote_total, dvTotal: @this_vote.review.downvote_total }
  end

  def before_vote
    @review = Review.find(params[:review_id])
    @this_vote = Vote.find_or_initialize_by(review: @review, user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def webseries_video(url)
    @post.link = url
    render :partial => 'video', :locals => { :url => url }
  end
end

app/views/admin/users/index.html.erb
<h1>Admin</h1>

<table>
  <thead>
    <tr>
      <th width="150">Username</th>
      <th width="200">Email</th>
      <th width="100">Delete?</th>
    </tr>
  </thead>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= button_to 'Delete User', admin_destroy_user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: "alert button expand" %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "SoTi" %></title>
    <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li class="has-form">
            <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
            <div class="row collapse">
              <div class="small-9 columns">
                <%= text_field_tag :search, params[:search], placeholder: "Search Web Series" %>
              </div>
              <div class="small-3 columns">
                <%= submit_tag "Search", :name => nil,  class: "alert button expand" %>
              </div>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <% if user_signed_in? %>
          <% if current_user.avatar.url.present? %>
          <li class="has-form" id="user_avatar"><%= image_tag(current_user.avatar.small_avatar) %></li>
          <% end %>
            <li class="has-form"><%= link_to "Update Information", edit_user_registration_path %></li>
            <li class="has-form"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% if current_user.admin? %>
              <li class="has-form"><%= link_to "Admin Section", admin_users_path %></li>
              <li class="has-form"><%= link_to "Root", root_path %></li>
            <% end %>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  <div>
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :class => "flash_#{name}" %>
      <% end %>
    <% end %>
  </div>
    <div class="small-10 columns small-centered" id="interior">
      <%= yield %>
    </div>
  </div>
</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <%= f.label :webseries_name, "Title" %><br>
  <%= f.text_field :webseries_name %>
  <br>
  <%= f.label :link, "Link to Webseries" %><br>
  <%= f.text_field :link %>
  <br>
  <%= f.label :description, "Description" %><br>
  <%= f.text_field :description %>
  <br>
  <%= f.submit 'Submit', class: "alert button expand" %>
<% end %>

app/views/posts/_review_form.html.erb
<%= form_for [@post, @review] do |f|%>
  <div class="field">
    <%= f.collection_radio_buttons :rating, @rating_options, :first, :last %>
  </div>

  <div class="field">
    <%= f.label :body, "Comments" %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <input name="commit" type="submit" value="Submit Review"/>
  </div>
<% end %>

app/views/posts/_video.html.erb
<iframe width="560" height="315" src="<%= url %>" frameborder="0" allowfullscreen></iframe>

app/views/posts/edit.html.erb
<h1><%= @post.webseries_name %>Edit Details</h1>
 <%= render "form" %>

 <br />

<%= button_to 'Back to Index', posts_path, method: :get, class: "alert button expand" %>

app/views/posts/index.html.erb
<div style="text-align: center">
  <h1><b>We Are State of the Indie!</b></h1>
  <h4>Destination for web-series' of all genres produced by independent artists.</h4>
  <h4><span><b>Sign up</b></span> and post your favorite series, make reviews, up or down vote, comment on listed reviews and share links to the <span><u>best series'</u></span> on the web!</h4>
</div>

<br />

<%= paginate @posts %>

<table>
  <thead>
    <tr style="font-weight: 500;">
      <th width="150">Series Title</th>
      <th width="200">Description</th>
      <% if current_user.try(:admin?) %>
        <th width="200">Delete?</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td style="font-weight: 800;"><%= link_to post.webseries_name, post_path(post) %></td>
          <td><%= post.description %></td>
          <% if current_user.try(:admin?) %>
            <td>
              <%= button_to 'Delete Post', post_path(post),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
            </td>
          <% end %>
        </tr>
      <% end %>
  </tbody>
</table>

<%= button_to 'Post a Series', new_post_path, method: :get, class: "alert button expand" %>

app/views/posts/new.html.erb
<h1>What Series would you like to post?</h1>
<%= render "form" %>

<br />

<%= button_to 'Back to Index', posts_path, method: :get %>

app/views/posts/show.html.erb
<br />
<%= button_to 'Back to Index', posts_path, method: :get, class: "alert button expand" %>

<div id="webseries_video_embed" style="text-align: center">
  <h1><b><%= @post.webseries_name %></b></h1>
  <br />
  <%= webseries_video @post.link %>
  <%= button_to "Visit series channel", @post.link, class: "alert button expand" %>
</div>

<br />

<h4><%= @post.description %></h4>

<% if !user_signed_in? %>
  <p>
    Please sign in to write a review.
    Please sign in to vote on a review.
  </p>
<% end %>

<%= paginate @reviews %>

<dl>
<% @reviews.each do |review| %>
  <dt><%=review.user.username %> says:</dt>
  <% if review.user == current_user && session[:edit] %>
      <% @review = review %>
      <%= render "review_form" %>
    <% elsif review.user == current_user || current_user.try(:admin?) %>
      <dd>Rating: <%=review.rating  %></dd>
      <dd>Review: <%=review.body  %></dd>
      <%= button_to "Edit Review", edit_post_review_path(@post, review), method: :get, class: "small alert button expand" %>
      <%= button_to "Delete Review", post_review_path(@post, review), method: :delete, class: "small alert button expand" %>
    <% else %>
      <dd>Rating: <%=review.rating  %></dd>
      <dd>Review: <%=review.body  %></dd>
    <% end %>
    <% if user_signed_in? %>
      <div class="vote-block" id="<%= review.id %>" >
        <%= button_to "Upvote", upvote_review_votes_path(review), id: 'uvote', class: "tiny alert button expand" %>
        Upvotes: <div class=uvTotal><%= review.upvote_total %></div>
        <%= button_to "Downvote", downvote_review_votes_path(review), id: 'dvote', class: "tiny alert button expand" %>
        Downvotes: <div class=dvTotal><%= review.downvote_total %></div>
        <% if current_user.voted?(review.id) %>
          <%= button_to "UnVote", unvote_review_votes_path(review), id: 'unvote' %>
        <% else %>
          <%= button_to "UnVote", unvote_review_votes_path(review), id: 'unvote', hidden: 'true' %>
        <% end %>
      </div>
    <% else %>
      <div class="vote-block" id="<%= review.id %>" >
        Upvotes: <%= review.upvote_total%>
        Downvotes: <%= review.downvote_total%>
      </div>
    <% end %>
  <br><br>
<% end %>
</dl>

<% @check = nil %>
<% @reviews.each do |review| %>
  <% if review.user == current_user %>
    <% @check = true %>
  <% end %>
<% end %>



<% if user_signed_in? && !@check %>
  <%= render "review_form" %>
<% end %>

<% session[:edit] = nil %>

<br />

<% if current_user == @post.user %>
  <div id="post_buttons" style="position: relative; top: 50%; transform: translateY(-50%);" >
    <table>
      <tr>
        <th>
          <%= button_to "Update this Post", edit_post_path(@post), method: :get %>
        </th>
        <th>
          <%= button_to "Delete this Post", post_path(@post), method: :delete %>
        </th>
        <th>
          <%= button_to 'Post an Series', new_post_path, method: :get %>
        </th>
        <th>
          <%= button_to 'Back to Index', posts_path, method: :get %>
        </th>
      </tr>
    </table>
  </div>
<% end %>